server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Статические ассеты — кешируем 1 год
    location ~* \.(js|css|png|jpg|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
